/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package idec.x.spesometro.utils;

import idec.x.spesometro.conn.Connessione;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;

/**
 *
 * @author Luca
 */
public class AggiustaTabelle {
    
    
    public static void aggiustaNull_2048pc(){
        
    }
    
    

    public static void aggiustaNull_2048pc(String db) throws SQLException {
        int i = 0;
        Connection conn = Connessione.getConnection(db);
        PreparedStatement preparedStmt;

        String query = " UPDATE " + db + ".\"2048pc\" SET cee_codice_cognome = '' WHERE cee_codice_cognome IS NULL ;\n";
        String query1 = " UPDATE " + db + ".\"2048pc\" SET cee_codice_nome = '' WHERE cee_codice_nome IS NULL ;\n";
        String query2 = " UPDATE " + db + ".\"2048pc\" SET comune = '0' WHERE comune IS NULL ;\n";
        String query3 = " UPDATE " + db + ".\"2048pc\" SET fisc_cod = '' WHERE fisc_cod IS NULL ;\n";

        preparedStmt = conn.prepareStatement(query);
        preparedStmt.executeUpdate();
        preparedStmt = conn.prepareStatement(query1);
        preparedStmt.executeUpdate();
        preparedStmt = conn.prepareStatement(query2);
        preparedStmt.executeUpdate();
        preparedStmt = conn.prepareStatement(query3);
        preparedStmt.executeUpdate();
    }

    public static void aggiustaNull2044(String db) throws SQLException {
        int i = 0;
        Connection conn = Connessione.getConnection(db);

        String query = "UPDATE " + db + ".\"2044mv\" SET despar = '0' WHERE despar IS NULL ";

        String query1 = "UPDATE " + db + ".\"2044mv\" SET cod_att = '0' WHERE cod_att IS NULL ";
        //String query2 = "UPDATE " + db + ".\"2044mv\" SET data_bil = '0' WHERE data_bil IS NULL ";
        String query3 = "UPDATE " + db + ".\"2044mv\" SET tipo_libro = '0' WHERE tipo_libro IS NULL ";
        String query4 = "UPDATE " + db + ".\"2044mv\" SET nome_libro = '0' WHERE nome_libro IS NULL ";
        String query5 = "UPDATE " + db + ".\"2044mv\" SET localita = '0' WHERE localita IS NULL ";
        String query6 = "UPDATE " + db + ".\"2044mv\" SET n_reg = '0' WHERE n_reg IS NULL ";
        String query7 = "UPDATE " + db + ".\"2044mv\" SET rigo = '0' WHERE rigo IS NULL ";
        String query8 = "UPDATE " + db + ".\"2044mv\" SET subrigo = '0' WHERE subrigo IS NULL ";
        String query9 = "UPDATE " + db + ".\"2044mv\" SET a_g = '0' WHERE a_g IS NULL ";
        String query10 = "UPDATE " + db + ".\"2044mv\" SET causele = '0' WHERE causele IS NULL ";
        String query11 = "UPDATE " + db + ".\"2044mv\" SET data_gio = data_bil WHERE data_gio IS NULL ";
        String query12 = "UPDATE " + db + ".\"2044mv\" SET bol_gio = '0' WHERE bol_gio IS NULL ";
        String query13 = "UPDATE " + db + ".\"2044mv\" SET bol_iva = '0' WHERE bol_iva IS NULL ";
        String query14 = "UPDATE " + db + ".\"2044mv\" SET divisa = '0' WHERE divisa IS NULL ";
        String query15 = "UPDATE " + db + ".\"2044mv\" SET doc_n = '0' WHERE doc_n IS NULL ";
        String query16 = "UPDATE " + db + ".\"2044mv\" SET data_doc = data_bil WHERE data_doc IS NULL ";
        String query17 = "UPDATE " + db + ".\"2044mv\" SET rif_doc = '0' WHERE rif_doc IS NULL ";
        String query18 = "UPDATE " + db + ".\"2044mv\" SET tipomastro = '0' WHERE tipomastro IS NULL ";
        String query19 = "UPDATE " + db + ".\"2044mv\" SET mastro = '0' WHERE mastro IS NULL ";
        String query20 = "UPDATE " + db + ".\"2044mv\" SET mastro2 = '0' WHERE mastro2 IS NULL ";
        String query21 = "UPDATE " + db + ".\"2044mv\" SET mastro3 = '0' WHERE mastro3 IS NULL ";
        String query22 = "UPDATE " + db + ".\"2044mv\" SET mastro4 = '0' WHERE mastro4 IS NULL ";
        String query23 = "UPDATE " + db + ".\"2044mv\" SET conto = '0' WHERE conto IS NULL ";
        String query24 = "UPDATE " + db + ".\"2044mv\" SET codice = '0' WHERE codice IS NULL ";
        String query25 = "UPDATE " + db + ".\"2044mv\" SET \"IMPORTO_DOC_DARE\" = '0' WHERE \"IMPORTO_DOC_DARE\" IS NULL ";
        String query26 = "UPDATE " + db + ".\"2044mv\" SET \"IMPORTO_DOC_AVERE\" = '0' WHERE \"IMPORTO_DOC_AVERE\" IS NULL ";
        String query27 = "UPDATE " + db + ".\"2044mv\" SET cambio = '0' WHERE cambio IS NULL ";
        String query28 = "UPDATE " + db + ".\"2044mv\" SET \"IMPORTO_EURO_DARE\" = '0' WHERE \"IMPORTO_EURO_DARE\" IS NULL ";
        String query29 = "UPDATE " + db + ".\"2044mv\" SET \"IMPORTO_EURO_AVERE\" = '0' WHERE \"IMPORTO_EURO_AVERE\" IS NULL ";
        String query30 = "UPDATE " + db + ".\"2044mv\" SET iva_cod = '0' WHERE iva_cod IS NULL ";
        String query31 = "UPDATE " + db + ".\"2044mv\" SET sezione_iva = '0' WHERE sezione_iva IS NULL ";
        String query32 = "UPDATE " + db + ".\"2044mv\" SET riv = '0' WHERE riv IS NULL ";
        String query33 = "UPDATE " + db + ".\"2044mv\" SET iva_perc = '0' WHERE iva_perc IS NULL ";
        String query34 = "UPDATE " + db + ".\"2044mv\" SET iva_perc_det = '0' WHERE iva_perc_det IS NULL ";
        String query35 = "UPDATE " + db + ".\"2044mv\" SET \"IVA_IMP_DET\" = '0' WHERE \"IVA_IMP_DET\" IS NULL ";
        String query36 = "UPDATE " + db + ".\"2044mv\" SET despar = '0' WHERE despar IS NULL ";
        String query37 = "UPDATE " + db + ".\"2044mv\" SET desconpar = '0' WHERE desconpar IS NULL ";
        String query38 = "UPDATE " + db + ".\"2044mv\" SET \"FUNZ_IVA\" = '0' WHERE \"FUNZ_IVA\" IS NULL ";
        String query39 = "UPDATE " + db + ".\"2044mv\" SET \"IMPORTO_CONTO\" = '0' WHERE \"IMPORTO_CONTO\" IS NULL ";
        String query40 = "UPDATE " + db + ".\"2044mv\" SET \"IMPORTO_DOCUMENTO\" = '0' WHERE \"IMPORTO_DOCUMENTO\" IS NULL ";
        String query41 = "UPDATE " + db + ".\"2044mv\" SET \"TOT_DARE\" = '0' WHERE \"TOT_DARE\" IS NULL ";
        String query42 = "UPDATE " + db + ".\"2044mv\" SET \"TOT_AVERE\" = '0' WHERE \"TOT_AVERE\" IS NULL ";
        String query43 = "UPDATE " + db + ".\"2044mv\" SET \"TOT_DIF\" = '0' WHERE \"TOT_DIF\" IS NULL ";
        String query44 = "UPDATE " + db + ".\"2044mv\" SET \"TOT_DIF_IVA\" = '0' WHERE \"TOT_DIF_IVA\" IS NULL ";
        String query45 = "UPDATE " + db + ".\"2044mv\" SET \"TOT_IMP\" = '0' WHERE \"TOT_IMP\" IS NULL ";
        String query46 = "UPDATE " + db + ".\"2044mv\" SET \"TOT_IVA\" = '0' WHERE \"TOT_IVA\" IS NULL ";
        String query47 = "UPDATE " + db + ".\"2044mv\" SET \"VALORE_CALCOLO\" = '0' WHERE \"VALORE_CALCOLO\" IS NULL ";
        String query48 = "UPDATE " + db + ".\"2044mv\" SET tipomastroiva = '0' WHERE tipomastroiva IS NULL ";
        String query49 = "UPDATE " + db + ".\"2044mv\" SET mastroiva = '0' WHERE mastroiva IS NULL ";
        String query50 = "UPDATE " + db + ".\"2044mv\" SET mastro2iva = '0' WHERE mastro2iva IS NULL ";
        String query51 = "UPDATE " + db + ".\"2044mv\" SET mastro3iva = '0' WHERE mastro3iva IS NULL ";
        String query52 = "UPDATE " + db + ".\"2044mv\" SET mastro4iva = '0' WHERE mastro4iva IS NULL ";
        String query53 = "UPDATE " + db + ".\"2044mv\" SET contoiva = '0' WHERE contoiva IS NULL ";
        String query54 = "UPDATE " + db + ".\"2044mv\" SET codiceiva = '0' WHERE codiceiva IS NULL ";
        String query55 = "UPDATE " + db + ".\"2044mv\" SET \"ARTICOLO_IVA_PERC\" = '0' WHERE \"ARTICOLO_IVA_PERC\" IS NULL ";
        String query56 = "UPDATE " + db + ".\"2044mv\" SET tipo_doc = '0' WHERE tipo_doc IS NULL ";
        String query57 = "UPDATE " + db + ".\"2044mv\" SET importo_euro = '0' WHERE importo_euro IS NULL ";
        String query58 = "UPDATE " + db + ".\"2044mv\" SET \"Totale\" = '0' WHERE \"Totale\" IS NULL ";
        String query59 = "UPDATE " + db + ".\"2044mv\" SET tm0 = '0' WHERE tm0 IS NULL ";
        String query60 = "UPDATE " + db + ".\"2044mv\" SET m0 = '0' WHERE m0 IS NULL ";
        String query61 = "UPDATE " + db + ".\"2044mv\" SET m20 = '0' WHERE m20 IS NULL ";
        String query62 = "UPDATE " + db + ".\"2044mv\" SET m30 = '0' WHERE m30 IS NULL ";
        String query63 = "UPDATE " + db + ".\"2044mv\" SET m40 = '0' WHERE m40 IS NULL ";
        String query64 = "UPDATE " + db + ".\"2044mv\" SET cnt0 = '0' WHERE cnt0 IS NULL ";
        String query65 = "UPDATE " + db + ".\"2044mv\" SET cod0 = '0' WHERE cod0 IS NULL ";
//*******
        String query66 = "UPDATE " + db + ".\"2044mv\" SET annocodtrib = '0' WHERE annocodtrib IS NULL ";
        String query67 = "UPDATE " + db + ".\"2044mv\" SET \"codTrib\" = '0' WHERE \"codTrib\" IS NULL ";
        String query68 = "UPDATE " + db + ".\"2044mv\" SET \"TipoAcquisti\" = '0' WHERE \"TipoAcquisti\" IS NULL ";
        String query69 = "UPDATE " + db + ".\"2044mv\" SET data_storno = data_bil WHERE data_storno IS NULL ";
        String query70 = "UPDATE " + db + ".\"2044mv\" SET data_rateo1 = data_bil WHERE data_rateo1 IS NULL ";
        String query71 = "UPDATE " + db + ".\"2044mv\" SET data_rateo2 = data_bil WHERE data_rateo2 IS NULL ";
        String query72 = "UPDATE " + db + ".\"2044mv\" SET f24_causale_contributo = '0' WHERE f24_causale_contributo IS NULL ";
        String query73 = "UPDATE " + db + ".\"2044mv\" SET mesecodtrib = '0' WHERE mesecodtrib IS NULL ";
        String query74 = "UPDATE " + db + ".\"2044mv\" SET tipo_libro_storno_accertamento = '0' WHERE tipo_libro_storno_accertamento IS NULL ";
        String query75 = "UPDATE " + db + ".\"2044mv\" SET nome_libro_storno_accertamento = '0' WHERE nome_libro_storno_accertamento IS NULL ";
        String query76 = "UPDATE " + db + ".\"2044mv\" SET causale_storno_accertamento = '0' WHERE causale_storno_accertamento IS NULL ";
        String query77 = "UPDATE " + db + ".\"2044mv\" SET num_reg_storno_accertamento = '0' WHERE num_reg_storno_accertamento IS NULL ";
        String query78 = "UPDATE " + db + ".\"2044mv\" SET data_storno_accertamento = data_bil WHERE data_storno_accertamento IS NULL ";
        String query79 = "UPDATE " + db + ".\"2044mv\" SET num_reg_competenza = '0' WHERE num_reg_competenza IS NULL ";
        String query80 = "UPDATE " + db + ".\"2044mv\" SET data_competenza = data_bil WHERE data_competenza IS NULL ";
        String query81 = "UPDATE " + db + ".\"2044mv\" SET tipomastro_storno_accertamento = '0' WHERE tipomastro_storno_accertamento IS NULL ";
        String query82 = "UPDATE " + db + ".\"2044mv\" SET mastro_storno_accertamento = '0' WHERE mastro_storno_accertamento IS NULL ";
        String query83 = "UPDATE " + db + ".\"2044mv\" SET mastro2_storno_accertamento = '0' WHERE mastro2_storno_accertamento IS NULL ";
        String query84 = "UPDATE " + db + ".\"2044mv\" SET mastro3_storno_accertamento = '0' WHERE mastro3_storno_accertamento IS NULL ";
        String query85 = "UPDATE " + db + ".\"2044mv\" SET mastro4_storno_accertamento = '0' WHERE mastro4_storno_accertamento IS NULL ";
        String query86 = "UPDATE " + db + ".\"2044mv\" SET conto_storno_accertamento = '0' WHERE conto_storno_accertamento IS NULL ";
        String query87 = "UPDATE " + db + ".\"2044mv\" SET codice_storno_accertamento = '0' WHERE codice_storno_accertamento IS NULL ";
        String query88 = "UPDATE " + db + ".\"2044mv\" SET importo_storno_accertamento = '0' WHERE importo_storno_accertamento IS NULL ";
        String query89 = "UPDATE " + db + ".\"2044mv\" SET tipo_pagamento = '0' WHERE tipo_pagamento IS NULL ";
        String query90 = "UPDATE " + db + ".\"2044mv\" SET cod_pagamento = '0' WHERE cod_pagamento IS NULL ";
        String query91 = "UPDATE " + db + ".\"2044mv\" SET rif_banca = '0' WHERE rif_banca IS NULL ";
        String query92 = "UPDATE " + db + ".\"2044mv\" SET ra_pagato = '0' WHERE ra_pagato IS NULL ";
        String query93 = "UPDATE " + db + ".\"2044mv\" SET totale_ra = '0' WHERE totale_ra IS NULL ";
        String query94 = "UPDATE " + db + ".\"2044mv\" SET \"checkPagato\" = '0' WHERE \"checkPagato\" IS NULL ";
        String query95 = "UPDATE " + db + ".\"2044mv\" SET \"checkStorno\"= '0' WHERE \"checkStorno\" IS NULL ";
        String query96 = "UPDATE " + db + ".\"2044mv\" SET \"checkRateo\" = '0' WHERE \"checkRateo\" IS NULL ";
        String query97 = "UPDATE " + db + ".\"2044mv\" SET \"checkCompetenza\" = '0' WHERE \"checkCompetenza\" IS NULL ";
        String query98 = "UPDATE " + db + ".\"2044mv\" SET utente = '0' WHERE utente IS NULL ";
        String query99 = "UPDATE " + db + ".\"2044mv\" SET data_utente = data_bil WHERE data_utente IS NULL ";
        String query100 = "UPDATE " + db + ".\"2044mv\" SET imp_non_soggetto_ra = '0' WHERE imp_non_soggetto_ra IS NULL ";
        String query101 = "UPDATE " + db + ".\"2044mv\" SET perc_trib_ra = '0' WHERE perc_trib_ra IS NULL ";
        String query102 = "UPDATE " + db + ".\"2044mv\" SET \"checkAccertamento\" = '0' WHERE \"checkAccertamento\" IS NULL ";
        String query103 = "UPDATE " + db + ".\"2044mv\" SET \"dataAccertamento\" = data_bil WHERE \"dataAccertamento\" IS NULL ";
        String query104 = "UPDATE " + db + ".\"2044mv\" SET \"tipomastroAccertamento\" = '0' WHERE \"tipomastroAccertamento\" IS NULL ";
        String query105 = "UPDATE " + db + ".\"2044mv\" SET \"mastroAccertamento\" = '0' WHERE \"mastroAccertamento\" IS NULL ";
        String query106 = "UPDATE " + db + ".\"2044mv\" SET \"mastro2Accertamento\" = '0' WHERE \"mastro2Accertamento\" IS NULL ";
        String query107 = "UPDATE " + db + ".\"2044mv\" SET \"mastro3Accertamento\" = '0' WHERE \"mastro3Accertamento\" IS NULL ";
        String query108 = "UPDATE " + db + ".\"2044mv\" SET \"mastro4Accertamento\" = '0' WHERE \"mastro4Accertamento\" IS NULL ";
        String query109 = "UPDATE " + db + ".\"2044mv\" SET \"contoAccertamento\" = '0' WHERE \"contoAccertamento\" IS NULL ";
        String query110 = "UPDATE " + db + ".\"2044mv\" SET \"codiceAccertamento\" = '0' WHERE \"codiceAccertamento\" IS NULL ";
        String query111 = "UPDATE " + db + ".\"2044mv\" SET \"numeroAccertamento\" = '0' WHERE \"numeroAccertamento\" IS NULL ";
        String query112 = "UPDATE " + db + ".\"2044mv\" SET \"rigoAccertamento\" = '0' WHERE \"rigoAccertamento\" IS NULL ";
        String query113 = "UPDATE " + db + ".\"2044mv\" SET \"checkDiversi\" = '0' WHERE \"checkDiversi\" IS NULL ";
        String query114 = "UPDATE " + db + ".\"2044mv\" SET data_storno_rateo = data_bil WHERE data_storno_rateo IS NULL ";
        String query115 = "UPDATE " + db + ".\"2044mv\" SET numero_storno_rateo = '0' WHERE numero_storno_rateo IS NULL ";
        String query116 = "UPDATE " + db + ".\"2044mv\" SET rigo_storno_rateo = '0' WHERE rigo_storno_rateo IS NULL ";
        String query117 = "UPDATE " + db + ".\"2044mv\" SET \"ripartoAcquisti\" = '0' WHERE \"ripartoAcquisti\" IS NULL ";
        String query118 = "UPDATE " + db + ".\"2044mv\" SET \"condizioniPagamento\" = '0' WHERE \"condizioniPagamento\" IS NULL ";
        String query119 = "UPDATE " + db + ".\"2044mv\" SET \"tipoPagamento\" = '0' WHERE \"tipoPagamento\" IS NULL ";
        String query120 = "UPDATE " + db + ".\"2044mv\" SET data_scadenza_fissa = data_bil WHERE data_scadenza_fissa IS NULL ";
        String query121 = "UPDATE " + db + ".\"2044mv\" SET da_griglia = '0' WHERE da_griglia IS NULL ";
        String query122 = "UPDATE " + db + ".\"2044mv\" SET iva_dati_riepilogo = '0' WHERE iva_dati_riepilogo IS NULL ";
        String query123 = "UPDATE " + db + ".\"2044mv\" SET imm_chk = '0' WHERE imm_chk IS NULL ";
        String query124 = "UPDATE " + db + ".\"2044mv\" SET imm_num_inv = '0' WHERE imm_num_inv IS NULL ";
        String query125 = "UPDATE " + db + ".\"2044mv\" SET num_scadenzario = '0' WHERE num_scadenzario IS NULL ";
        String query126 = "UPDATE " + db + ".\"2044mv\" SET rif_scadenzario = '0' WHERE rif_scadenzario IS NULL ";
        String query127 = "UPDATE " + db + ".\"2044mv\" SET \"tipoPerc\" = '0' WHERE \"tipoPerc\" IS NULL ";
        String query128 = "UPDATE " + db + ".\"2044mv\" SET \"percIidd\" = '0' WHERE \"percIidd\" IS NULL ";
        String query129 = "UPDATE " + db + ".\"2044mv\" SET \"percIrap\" = '0' WHERE \"percIrap\" IS NULL ";
        String query130 = "UPDATE " + db + ".\"2044mv\" SET importo_lit_dare = '0' WHERE importo_lit_dare IS NULL ";
        String query131 = "UPDATE " + db + ".\"2044mv\" SET importo_lit_avere = '0' WHERE importo_lit_avere IS NULL ";
        String query132 = "UPDATE " + db + ".\"2044mv\" SET iva_imp_det_lit = '0' WHERE iva_imp_det_lit IS NULL ";
        String query133 = "UPDATE " + db + ".\"2044mv\" SET max_fis = '0' WHERE max_fis IS NULL ";
        String query134 = "UPDATE " + db + ".\"2044mv\" SET cod_trib_21 = '0' WHERE cod_trib_21 IS NULL ";
        String query135 = "UPDATE " + db + ".\"2044mv\" SET anno_cod_trib_21 = '0' WHERE anno_cod_trib_21 IS NULL ";
        String query136 = "UPDATE " + db + ".\"2044mv\" SET mese_cod_trib_21 = '0' WHERE mese_cod_trib_21 IS NULL ";
        String query137 = "UPDATE " + db + ".\"2044mv\" SET imp_ra_21 = '0' WHERE imp_ra_21 IS NULL ";
        String query138 = "UPDATE " + db + ".\"2044mv\" SET non_imp_ra_21 = '0' WHERE non_imp_ra_21 IS NULL ";
        String query139 = "UPDATE " + db + ".\"2044mv\" SET perc_ra_21 = '0' WHERE perc_ra_21 IS NULL ";
        String query140 = "UPDATE " + db + ".\"2044mv\" SET tm_21 = '0' WHERE tm_21 IS NULL ";
        String query141 = "UPDATE " + db + ".\"2044mv\" SET m_21 = '0' WHERE m_21 IS NULL ";
        String query142 = "UPDATE " + db + ".\"2044mv\" SET m2_21 = '0' WHERE m2_21 IS NULL ";
        String query143 = "UPDATE " + db + ".\"2044mv\" SET m3_21 = '0' WHERE m3_21 IS NULL ";
        String query144 = "UPDATE " + db + ".\"2044mv\" SET m4_21 = '0' WHERE m4_21 IS NULL ";
        String query145 = "UPDATE " + db + ".\"2044mv\" SET cnt_21 = '0' WHERE cnt_21 IS NULL ";
        String query146 = "UPDATE " + db + ".\"2044mv\" SET cod_21 = '0' WHERE cod_21 IS NULL ";
        String query147 = "UPDATE " + db + ".\"2044mv\" SET check_rata_personale = '0' WHERE check_rata_personale IS NULL ";
        String query148 = "UPDATE " + db + ".\"2044mv\" SET check_calcolatrice = '0' WHERE check_calcolatrice IS NULL ";
        String query149 = "UPDATE " + db + ".\"2044mv\" SET entro1anno = '0' WHERE entro1anno IS NULL ";
        String query150 = "UPDATE " + db + ".\"2044mv\" SET oltre1anno = '0' WHERE oltre1anno IS NULL ";
        String query151 = "UPDATE " + db + ".\"2044mv\" SET entro5anni = '0' WHERE entro5anni IS NULL ";
        String query152 = "UPDATE " + db + ".\"2044mv\" SET oltre5anni = '0' WHERE oltre5anni IS NULL ";
        String query153 = "UPDATE " + db + ".\"2044mv\" SET \"descrizioneRateo\" = '0' WHERE \"descrizioneRateo\" IS NULL ";
        String query154 = "UPDATE " + db + ".\"2044mv\" SET \"numRateo\" = '0' WHERE \"numRateo\" IS NULL ";
        String query155 = "UPDATE " + db + ".\"2044mv\" SET oggetto_iidd = '0' WHERE oggetto_iidd IS NULL ";
        String query156 = "UPDATE " + db + ".\"2044mv\" SET oggetto_irap = '0' WHERE oggetto_irap IS NULL ";
        String query157 = "UPDATE " + db + ".\"2044mv\" SET oggetto_iva = '0' WHERE oggetto_iva IS NULL ";
        String query158 = "UPDATE " + db + ".\"2044mv\" SET iva_non_imponibile = '0' WHERE iva_non_imponibile IS NULL ";
        String query159 = "UPDATE " + db + ".\"2044mv\" SET iva_perc_non_imponibile = '0' WHERE iva_perc_non_imponibile IS NULL ";
        String query160 = "UPDATE " + db + ".\"2044mv\" SET condizione_pilota = '0' WHERE condizione_pilota IS NULL ";
        String query161 = "UPDATE " + db + ".\"2044mv\" SET data_scadenza_cod_trib = data_bil WHERE data_scadenza_cod_trib IS NULL ";
        String query162 = "UPDATE " + db + ".\"2044mv\" SET imponibile_indicativo = '0' WHERE imponibile_indicativo IS NULL ";
        String query163 = "UPDATE " + db + ".\"2044mv\" SET causale_pagamento_ra = '0' WHERE causale_pagamento_ra IS NULL ";
        String query164 = "UPDATE " + db + ".\"2044mv\" SET perc_riduzione_ra = '0' WHERE perc_riduzione_ra IS NULL ";
        String query165 = "UPDATE " + db + ".\"2044mv\" SET riduzione_ra = '0' WHERE riduzione_ra IS NULL ";
        String query166 = "UPDATE " + db + ".\"2044mv\" SET num_reg_iva_integrata = '0' WHERE num_reg_iva_integrata IS NULL ";
        String query167 = "UPDATE " + db + ".\"2044mv\" SET numeratore_iidd = '0' WHERE numeratore_iidd IS NULL ";
        String query168 = "UPDATE " + db + ".\"2044mv\" SET denominatore_iidd = '0' WHERE denominatore_iidd IS NULL ";
        String query169 = "UPDATE " + db + ".\"2044mv\" SET numeratore_irap = '0' WHERE numeratore_irap IS NULL ";
        String query170 = "UPDATE " + db + ".\"2044mv\" SET denominatore_irap = '0' WHERE denominatore_irap IS NULL ";
        String query171 = "UPDATE " + db + ".\"2044mv\" SET iva_per_quadratura = '0' WHERE iva_per_quadratura IS NULL ";
        String query172 = "UPDATE " + db + ".\"2044mv\" SET soggetto_iidd = '0' WHERE soggetto_iidd IS NULL ";
        String query173 = "UPDATE " + db + ".\"2044mv\" SET soggetto_irap = '0' WHERE soggetto_irap IS NULL ";
        String query174 = "UPDATE " + db + ".\"2044mv\" SET soggetto_iva = '0' WHERE soggetto_iva IS NULL ";
        String query175 = "UPDATE " + db + ".\"2044mv\" SET utente_data = data_bil WHERE utente_data IS NULL ";
        String query176 = "UPDATE " + db + ".\"2044mv\" SET utente_modifica = '0' WHERE utente_modifica IS NULL ";
        String query177 = "UPDATE " + db + ".\"2044mv\" SET utente_data_modifica = data_bil WHERE utente_data_modifica IS NULL ";

        PreparedStatement preparedStmt;
        preparedStmt = conn.prepareStatement(query);
        preparedStmt.executeUpdate();

        preparedStmt = conn.prepareStatement(query1);
        System.out.println(1);
        preparedStmt.executeUpdate();
//        preparedStmt = conn.prepareStatement(query2);
//        System.out.println(2);
//        preparedStmt.executeUpdate();
        preparedStmt = conn.prepareStatement(query3);
        System.out.println(3);
        preparedStmt.executeUpdate();
        preparedStmt = conn.prepareStatement(query4);
        System.out.println(4);
        preparedStmt.executeUpdate();
        preparedStmt = conn.prepareStatement(query5);
        System.out.println(5);
        preparedStmt.executeUpdate();
        preparedStmt = conn.prepareStatement(query6);
        System.out.println(6);
        preparedStmt.executeUpdate();
        preparedStmt = conn.prepareStatement(query7);
        System.out.println(7);
        preparedStmt.executeUpdate();
        preparedStmt = conn.prepareStatement(query8);
        System.out.println(8);
        preparedStmt.executeUpdate();
        preparedStmt = conn.prepareStatement(query9);
        System.out.println(9);
        preparedStmt.executeUpdate();
        preparedStmt = conn.prepareStatement(query10);
        System.out.println(10);
        preparedStmt.executeUpdate();
        preparedStmt = conn.prepareStatement(query11);
        System.out.println(11);
        preparedStmt.executeUpdate();
        preparedStmt = conn.prepareStatement(query12);
        System.out.println(12);
        preparedStmt.executeUpdate();
        preparedStmt = conn.prepareStatement(query13);
        System.out.println(13);
        preparedStmt.executeUpdate();
        preparedStmt = conn.prepareStatement(query14);
        System.out.println(14);
        preparedStmt.executeUpdate();
        preparedStmt = conn.prepareStatement(query15);
        System.out.println(15);
        preparedStmt.executeUpdate();
        preparedStmt = conn.prepareStatement(query16);
        System.out.println(16);
        preparedStmt.executeUpdate();
        preparedStmt = conn.prepareStatement(query17);
        System.out.println(17);
        preparedStmt.executeUpdate();
        preparedStmt = conn.prepareStatement(query18);
        System.out.println(18);
        preparedStmt.executeUpdate();
        preparedStmt = conn.prepareStatement(query19);
        System.out.println(19);
        preparedStmt.executeUpdate();
        preparedStmt = conn.prepareStatement(query20);
        System.out.println(20);
        preparedStmt.executeUpdate();
        preparedStmt = conn.prepareStatement(query21);
        System.out.println(21);
        preparedStmt.executeUpdate();
        preparedStmt = conn.prepareStatement(query22);
        System.out.println(22);
        preparedStmt.executeUpdate();
        preparedStmt = conn.prepareStatement(query23);
        System.out.println(23);
        preparedStmt.executeUpdate();
        preparedStmt = conn.prepareStatement(query24);
        System.out.println(24);
        preparedStmt.executeUpdate();
        preparedStmt = conn.prepareStatement(query25);
        System.out.println(25);
        preparedStmt.executeUpdate();
        preparedStmt = conn.prepareStatement(query26);
        System.out.println(26);
        preparedStmt.executeUpdate();
        preparedStmt = conn.prepareStatement(query27);
        System.out.println(27);
        preparedStmt.executeUpdate();
        preparedStmt = conn.prepareStatement(query28);
        System.out.println(28);
        preparedStmt.executeUpdate();
        preparedStmt = conn.prepareStatement(query29);
        System.out.println(29);
        preparedStmt.executeUpdate();
        preparedStmt = conn.prepareStatement(query30);
        System.out.println(30);
        preparedStmt.executeUpdate();
        preparedStmt = conn.prepareStatement(query31);
        System.out.println(31);
        preparedStmt.executeUpdate();
        preparedStmt = conn.prepareStatement(query32);
        System.out.println(32);
        preparedStmt.executeUpdate();
        preparedStmt = conn.prepareStatement(query33);
        System.out.println(33);
        preparedStmt.executeUpdate();
        preparedStmt = conn.prepareStatement(query34);
        System.out.println(34);
        preparedStmt.executeUpdate();
        preparedStmt = conn.prepareStatement(query35);
        System.out.println(35);
        preparedStmt.executeUpdate();
        preparedStmt = conn.prepareStatement(query36);
        System.out.println(36);
        preparedStmt.executeUpdate();
        preparedStmt = conn.prepareStatement(query37);
        System.out.println(37);
        preparedStmt.executeUpdate();
        preparedStmt = conn.prepareStatement(query38);
        System.out.println(38);
        preparedStmt.executeUpdate();
        preparedStmt = conn.prepareStatement(query39);
        System.out.println(39);
        preparedStmt.executeUpdate();
        preparedStmt = conn.prepareStatement(query40);
        System.out.println(40);
        preparedStmt.executeUpdate();
        preparedStmt = conn.prepareStatement(query41);
        System.out.println(41);
        preparedStmt.executeUpdate();
        preparedStmt = conn.prepareStatement(query42);
        System.out.println(42);
        preparedStmt.executeUpdate();
        preparedStmt = conn.prepareStatement(query43);
        System.out.println(43);
        preparedStmt.executeUpdate();
        preparedStmt = conn.prepareStatement(query44);
        System.out.println(44);
        preparedStmt.executeUpdate();
        preparedStmt = conn.prepareStatement(query45);
        System.out.println(45);
        preparedStmt.executeUpdate();
        preparedStmt = conn.prepareStatement(query46);
        System.out.println(46);
        preparedStmt.executeUpdate();
        preparedStmt = conn.prepareStatement(query47);
        System.out.println(47);
        preparedStmt.executeUpdate();
        preparedStmt = conn.prepareStatement(query48);
        System.out.println(48);
        preparedStmt.executeUpdate();
        preparedStmt = conn.prepareStatement(query49);
        System.out.println(49);
        preparedStmt.executeUpdate();
        preparedStmt = conn.prepareStatement(query50);
        System.out.println(50);
        preparedStmt.executeUpdate();
        preparedStmt = conn.prepareStatement(query51);
        System.out.println(51);
        preparedStmt.executeUpdate();
        preparedStmt = conn.prepareStatement(query52);
        System.out.println(52);
        preparedStmt.executeUpdate();
        preparedStmt = conn.prepareStatement(query53);
        System.out.println(53);
        preparedStmt.executeUpdate();
        preparedStmt = conn.prepareStatement(query54);
        System.out.println(54);
        preparedStmt.executeUpdate();
        preparedStmt = conn.prepareStatement(query55);
        System.out.println(55);
        preparedStmt.executeUpdate();
        preparedStmt = conn.prepareStatement(query56);
        System.out.println(56);
        preparedStmt.executeUpdate();
        preparedStmt = conn.prepareStatement(query57);
        System.out.println(57);
        preparedStmt.executeUpdate();
        preparedStmt = conn.prepareStatement(query58);
        System.out.println(58);
        preparedStmt.executeUpdate();
        preparedStmt = conn.prepareStatement(query59);
        System.out.println(59);
        preparedStmt.executeUpdate();
        preparedStmt = conn.prepareStatement(query60);
        System.out.println(60);
        preparedStmt.executeUpdate();
        preparedStmt = conn.prepareStatement(query61);
        System.out.println(61);
        preparedStmt.executeUpdate();
        preparedStmt = conn.prepareStatement(query62);
        System.out.println(62);
        preparedStmt.executeUpdate();
        preparedStmt = conn.prepareStatement(query63);
        System.out.println(63);
        preparedStmt.executeUpdate();
        preparedStmt = conn.prepareStatement(query64);
        System.out.println(64);
        preparedStmt.executeUpdate();
        preparedStmt = conn.prepareStatement(query65);
        System.out.println(65);
        preparedStmt.executeUpdate();
        preparedStmt = conn.prepareStatement(query66);
        System.out.println(66);
        preparedStmt.executeUpdate();
        preparedStmt = conn.prepareStatement(query67);
        System.out.println(67);
        preparedStmt.executeUpdate();
        preparedStmt = conn.prepareStatement(query68);
        System.out.println(68);
        preparedStmt.executeUpdate();
        preparedStmt = conn.prepareStatement(query69);
        System.out.println(69);
        preparedStmt.executeUpdate();
        preparedStmt = conn.prepareStatement(query70);
        System.out.println(70);
        preparedStmt.executeUpdate();
        preparedStmt = conn.prepareStatement(query71);
        System.out.println(71);
        preparedStmt.executeUpdate();
        preparedStmt = conn.prepareStatement(query72);
        System.out.println(72);
        preparedStmt.executeUpdate();
        preparedStmt = conn.prepareStatement(query73);
        System.out.println(73);
        preparedStmt.executeUpdate();
        preparedStmt = conn.prepareStatement(query74);
        System.out.println(74);
        preparedStmt.executeUpdate();
        preparedStmt = conn.prepareStatement(query75);
        System.out.println(75);
        preparedStmt.executeUpdate();
        preparedStmt = conn.prepareStatement(query76);
        System.out.println(76);
        preparedStmt.executeUpdate();
        preparedStmt = conn.prepareStatement(query77);
        System.out.println(77);
        preparedStmt.executeUpdate();
        preparedStmt = conn.prepareStatement(query78);
        System.out.println(78);
        preparedStmt.executeUpdate();
        preparedStmt = conn.prepareStatement(query79);
        System.out.println(79);
        preparedStmt.executeUpdate();
        preparedStmt = conn.prepareStatement(query80);
        System.out.println(80);
        preparedStmt.executeUpdate();
        preparedStmt = conn.prepareStatement(query81);
        System.out.println(81);
        preparedStmt.executeUpdate();
        preparedStmt = conn.prepareStatement(query82);
        System.out.println(82);
        preparedStmt.executeUpdate();
        preparedStmt = conn.prepareStatement(query83);
        System.out.println(83);
        preparedStmt.executeUpdate();
        preparedStmt = conn.prepareStatement(query84);
        System.out.println(84);
        preparedStmt.executeUpdate();
        preparedStmt = conn.prepareStatement(query85);
        System.out.println(85);
        preparedStmt.executeUpdate();
        preparedStmt = conn.prepareStatement(query86);
        System.out.println(86);
        preparedStmt.executeUpdate();
        preparedStmt = conn.prepareStatement(query87);
        System.out.println(87);
        preparedStmt.executeUpdate();
        preparedStmt = conn.prepareStatement(query88);
        System.out.println(88);
        preparedStmt.executeUpdate();
        preparedStmt = conn.prepareStatement(query89);
        System.out.println(89);
        preparedStmt.executeUpdate();
        preparedStmt = conn.prepareStatement(query90);
        System.out.println(90);
        preparedStmt.executeUpdate();
        preparedStmt = conn.prepareStatement(query91);
        System.out.println(91);
        preparedStmt.executeUpdate();
        preparedStmt = conn.prepareStatement(query92);
        System.out.println(92);
        preparedStmt.executeUpdate();
        preparedStmt = conn.prepareStatement(query93);
        System.out.println(93);
        preparedStmt.executeUpdate();
        preparedStmt = conn.prepareStatement(query94);
        System.out.println(94);
        preparedStmt.executeUpdate();
        preparedStmt = conn.prepareStatement(query95);
        System.out.println(95);
        preparedStmt.executeUpdate();
        preparedStmt = conn.prepareStatement(query96);
        System.out.println(96);
        preparedStmt.executeUpdate();
        preparedStmt = conn.prepareStatement(query97);
        System.out.println(97);
        preparedStmt.executeUpdate();
        preparedStmt = conn.prepareStatement(query98);
        System.out.println(98);
        preparedStmt.executeUpdate();
        preparedStmt = conn.prepareStatement(query99);
        System.out.println(99);
        preparedStmt.executeUpdate();
        preparedStmt = conn.prepareStatement(query100);
        System.out.println(100);
        preparedStmt.executeUpdate();
        preparedStmt = conn.prepareStatement(query101);
        System.out.println(101);
        preparedStmt.executeUpdate();
        preparedStmt = conn.prepareStatement(query102);
        System.out.println(102);
        preparedStmt.executeUpdate();
        preparedStmt = conn.prepareStatement(query103);
        System.out.println(103);
        preparedStmt.executeUpdate();
        preparedStmt = conn.prepareStatement(query104);
        System.out.println(104);
        preparedStmt.executeUpdate();
        preparedStmt = conn.prepareStatement(query105);
        System.out.println(105);
        preparedStmt.executeUpdate();
        preparedStmt = conn.prepareStatement(query106);
        System.out.println(106);
        preparedStmt.executeUpdate();
        preparedStmt = conn.prepareStatement(query107);
        System.out.println(107);
        preparedStmt.executeUpdate();
        preparedStmt = conn.prepareStatement(query108);
        System.out.println(108);
        preparedStmt.executeUpdate();
        preparedStmt = conn.prepareStatement(query109);
        System.out.println(109);
        preparedStmt.executeUpdate();
        preparedStmt = conn.prepareStatement(query110);
        System.out.println(110);
        preparedStmt.executeUpdate();
        preparedStmt = conn.prepareStatement(query111);
        System.out.println(111);
        preparedStmt.executeUpdate();
        preparedStmt = conn.prepareStatement(query112);
        System.out.println(112);
        preparedStmt.executeUpdate();
        preparedStmt = conn.prepareStatement(query113);
        System.out.println(113);
        preparedStmt.executeUpdate();
        preparedStmt = conn.prepareStatement(query114);
        System.out.println(114);
        preparedStmt.executeUpdate();
        preparedStmt = conn.prepareStatement(query115);
        System.out.println(115);
        preparedStmt.executeUpdate();
        preparedStmt = conn.prepareStatement(query116);
        System.out.println(116);
        preparedStmt.executeUpdate();
        preparedStmt = conn.prepareStatement(query117);
        System.out.println(117);
        preparedStmt.executeUpdate();
        preparedStmt = conn.prepareStatement(query118);
        System.out.println(118);
        preparedStmt.executeUpdate();
        preparedStmt = conn.prepareStatement(query119);
        System.out.println(119);
        preparedStmt.executeUpdate();
        preparedStmt = conn.prepareStatement(query120);
        System.out.println(120);
        preparedStmt.executeUpdate();
        preparedStmt = conn.prepareStatement(query121);
        System.out.println(121);
        preparedStmt.executeUpdate();
        preparedStmt = conn.prepareStatement(query122);
        System.out.println(122);
        preparedStmt.executeUpdate();
        preparedStmt = conn.prepareStatement(query123);
        System.out.println(123);
        preparedStmt.executeUpdate();
        preparedStmt = conn.prepareStatement(query124);
        System.out.println(124);
        preparedStmt.executeUpdate();
        preparedStmt = conn.prepareStatement(query125);
        System.out.println(125);
        preparedStmt.executeUpdate();
        preparedStmt = conn.prepareStatement(query126);
        System.out.println(126);
        preparedStmt.executeUpdate();
        preparedStmt = conn.prepareStatement(query127);
        System.out.println(127);
        preparedStmt.executeUpdate();
        preparedStmt = conn.prepareStatement(query128);
        System.out.println(128);
        preparedStmt.executeUpdate();
        preparedStmt = conn.prepareStatement(query129);
        System.out.println(129);
        preparedStmt.executeUpdate();
        preparedStmt = conn.prepareStatement(query130);
        System.out.println(130);
        preparedStmt.executeUpdate();
        preparedStmt = conn.prepareStatement(query131);
        System.out.println(131);
        preparedStmt.executeUpdate();
        preparedStmt = conn.prepareStatement(query132);
        System.out.println(132);
        preparedStmt.executeUpdate();
        preparedStmt = conn.prepareStatement(query133);
        System.out.println(133);
        preparedStmt.executeUpdate();
        preparedStmt = conn.prepareStatement(query134);
        System.out.println(134);
        preparedStmt.executeUpdate();
        preparedStmt = conn.prepareStatement(query135);
        System.out.println(135);
        preparedStmt.executeUpdate();
        preparedStmt = conn.prepareStatement(query136);
        System.out.println(136);
        preparedStmt.executeUpdate();
        preparedStmt = conn.prepareStatement(query137);
        System.out.println(137);
        preparedStmt.executeUpdate();
        preparedStmt = conn.prepareStatement(query138);
        System.out.println(138);
        preparedStmt.executeUpdate();
        preparedStmt = conn.prepareStatement(query139);
        System.out.println(139);
        preparedStmt.executeUpdate();
        preparedStmt = conn.prepareStatement(query140);
        System.out.println(140);
        preparedStmt.executeUpdate();
        preparedStmt = conn.prepareStatement(query141);
        System.out.println(141);
        preparedStmt.executeUpdate();
        preparedStmt = conn.prepareStatement(query142);
        System.out.println(142);
        preparedStmt.executeUpdate();
        preparedStmt = conn.prepareStatement(query143);
        System.out.println(143);
        preparedStmt.executeUpdate();
        preparedStmt = conn.prepareStatement(query144);
        System.out.println(144);
        preparedStmt.executeUpdate();
        preparedStmt = conn.prepareStatement(query145);
        System.out.println(145);
        preparedStmt.executeUpdate();
        preparedStmt = conn.prepareStatement(query146);
        System.out.println(146);
        preparedStmt.executeUpdate();
        preparedStmt = conn.prepareStatement(query147);
        System.out.println(147);
        preparedStmt.executeUpdate();
        preparedStmt = conn.prepareStatement(query148);
        System.out.println(148);
        preparedStmt.executeUpdate();
        preparedStmt = conn.prepareStatement(query149);
        System.out.println(149);
        preparedStmt.executeUpdate();
        preparedStmt = conn.prepareStatement(query150);
        System.out.println(150);
        preparedStmt.executeUpdate();
        preparedStmt = conn.prepareStatement(query151);
        System.out.println(151);
        preparedStmt.executeUpdate();
        preparedStmt = conn.prepareStatement(query152);
        System.out.println(152);
        preparedStmt.executeUpdate();
        preparedStmt = conn.prepareStatement(query153);
        System.out.println(153);
        preparedStmt.executeUpdate();
        preparedStmt = conn.prepareStatement(query154);
        System.out.println(154);
        preparedStmt.executeUpdate();
        preparedStmt = conn.prepareStatement(query155);
        System.out.println(155);
        preparedStmt.executeUpdate();
        preparedStmt = conn.prepareStatement(query156);
        System.out.println(156);
        preparedStmt.executeUpdate();
        preparedStmt = conn.prepareStatement(query157);
        System.out.println(157);
        preparedStmt.executeUpdate();
        preparedStmt = conn.prepareStatement(query158);
        System.out.println(158);
        preparedStmt.executeUpdate();
        preparedStmt = conn.prepareStatement(query159);
        System.out.println(159);
        preparedStmt.executeUpdate();
        preparedStmt = conn.prepareStatement(query160);
        System.out.println(160);
        preparedStmt.executeUpdate();
        preparedStmt = conn.prepareStatement(query161);
        System.out.println(161);
        preparedStmt.executeUpdate();
        preparedStmt = conn.prepareStatement(query162);
        System.out.println(162);
        preparedStmt.executeUpdate();
        preparedStmt = conn.prepareStatement(query163);
        System.out.println(163);
        preparedStmt.executeUpdate();
        preparedStmt = conn.prepareStatement(query164);
        System.out.println(164);
        preparedStmt.executeUpdate();
        preparedStmt = conn.prepareStatement(query165);
        System.out.println(165);
        preparedStmt.executeUpdate();
        preparedStmt = conn.prepareStatement(query166);
        System.out.println(166);
        preparedStmt.executeUpdate();
        preparedStmt = conn.prepareStatement(query167);
        System.out.println(167);
        preparedStmt.executeUpdate();
        preparedStmt = conn.prepareStatement(query168);
        System.out.println(168);
        preparedStmt.executeUpdate();
        preparedStmt = conn.prepareStatement(query169);
        System.out.println(169);
        preparedStmt.executeUpdate();
        preparedStmt = conn.prepareStatement(query170);
        System.out.println(170);
        preparedStmt.executeUpdate();
        preparedStmt = conn.prepareStatement(query171);
        System.out.println(171);
        preparedStmt.executeUpdate();
        preparedStmt = conn.prepareStatement(query172);
        System.out.println(172);
        preparedStmt.executeUpdate();
        preparedStmt = conn.prepareStatement(query173);
        System.out.println(173);
        preparedStmt.executeUpdate();
        preparedStmt = conn.prepareStatement(query174);
        System.out.println(174);
        preparedStmt.executeUpdate();
        preparedStmt = conn.prepareStatement(query175);
        System.out.println(175);
        preparedStmt.executeUpdate();
        preparedStmt = conn.prepareStatement(query176);
        System.out.println(176);
        preparedStmt.executeUpdate();
        preparedStmt = conn.prepareStatement(query177);
        System.out.println(177);
        preparedStmt.executeUpdate();

    }

}
